spring:
  application:
    name: dracolich-library-api
  webflux:
    base-path: dracolich-library/api/v0/
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    database: ${MONGODB_DATABASE:dracolich-library-db}
    uri: ${MONGODB_URI:mongodb://localhost:27017/dracolich-library-db}
    representation:
      uuid: standard

server:
  port: ${PORT:8080}

logging:
  level:
    dm.dracolich: DEBUG
    org.springframework.data.mongodb: INFO
